# Get the endpoint from RDS Console ? Your DB ? Connectivity & security
app.base.url=${APP_URL}
spring.datasource.url=jdbc:mysql://${DB_DOMAIN}:${DB_PORT}/${DATABASE_NAME}?useSSL=true&requireSSL=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${SERVER_PORT}
# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# AWS ElastiCache Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# If you enabled "In-Transit Encryption" (TLS) in AWS
spring.data.redis.ssl.enabled=true